export const RECEIPT_CREATE_REQUEST = 'RECEIPT_CREATE_REQUEST'
export const RECEIPT_CREATE_SUCCESS = 'RECEIPT_CREATE_SUCCESS'
export const RECEIPT_CREATE_FAIL = 'RECEIPT_CREATE_FAIL'
export const RECEIPT_CREATE_RESET = 'RECEIPT_CREATE_RESET'

export const RECEIPT_CANCEL_REQUEST = 'RECEIPT_CANCEL_REQUEST'
export const RECEIPT_CANCEL_SUCCESS = 'RECEIPT_CANCEL_SUCCESS'
export const RECEIPT_CANCEL_FAIL = 'RECEIPT_CANCEL_FAIL'
export const RECEIPT_CANCEL_RESET = 'RECEIPT_CANCEL_RESET'

export const RECEIPT_DETAILS_REQUEST = 'RECEIPT_DETAILS_REQUEST'
export const RECEIPT_DETAILS_SUCCESS = 'RECEIPT_DETAILS_SUCCESS'
export const RECEIPT_DETAILS_FAIL = 'RECEIPT_DETAILS_FAIL'
export const RECEIPT_DETAILS_RESET = 'RECEIPT_DETAILS_RESET'

export const RECEIPT_LIST_REQUEST = 'RECEIPT_LIST_REQUEST'
export const RECEIPT_LIST_SUCCESS = 'RECEIPT_LIST_SUCCESS'
export const RECEIPT_LIST_FAIL = 'RECEIPT_LIST_FAIL'

export const RECEIPT_RECEIVE_REQUEST = 'RECEIPT_RECEIVE_REQUEST'
export const RECEIPT_RECEIVE_SUCCESS = 'RECEIPT_RECEIVE_SUCCESS'
export const RECEIPT_RECEIVE_FAIL = 'RECEIPT_RECEIVE_FAIL'
export const RECEIPT_RECEIVE_RESET = 'RECEIPT_RECEIVE_RESET'

export const RECEIPT_CART_ADD_ITEM = 'RECEIPT_CART_ADD_ITEM'
export const RECEIPT_CART_CLEAR_ITEMS = 'RECEIPT_CART_RESET'
export const RECEIPT_CART_REMOVE_ITEM = 'RECEIPT_CART_REMOVE_ITEM'
export const RECEIPT_CART_SAVE_SUPPLIER = 'RECEIPT_CART_SAVE_SUPPLIER'